version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 24
    commands:
      - echo 'Running Scripts'
      - corepack enable
      - corepack prepare pnpm@latest
      - aws codeartifact login --tool npm --repository registry-prod-repo --domain registry-prod --domain-owner 904690835784 --region eu-west-2
      - pnpm ci
      - ls
      - pnpm run test:e2e
