name: Testing E2E (for private Api Gateway)

permissions:
  contents: read
  id-token: write

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        description: 'Github environment to use'
        type: string
        required: true
      VERSION:
        description: 'Version label'
        type: string
        required: true

jobs:
  test:
    name: E2E (Codebuild)
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.ENVIRONMENT }}
    steps:
      - name: ⚙️ Checkout Code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Show OIDC claims (right before assume)
        if: ${{ runner.debug }}
        env:
          AUDIENCE: 'sts.amazonaws.com'
        run: |
          TOKEN_JSON=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=$AUDIENCE")
          ID_TOKEN=$(echo "$TOKEN_JSON" | jq -r .value)
          echo "$ID_TOKEN" | awk -F. '{print $2}' | base64 -d 2>/dev/null | jq -r '.sub'

      - name: ⚙️ Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e6de054238d6b7531b4efff3b6587d9aade6a06c # v6.2.3
        with:
          audience: sts.amazonaws.com
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: Upload source for e2e CodeBuild run
        run: |
          zip -rqy source.zip . 
          SOURCE_KEY="e2e/${{github.ref_name}}/source-${{github.run_id}}-${{github.sha}}"
          aws s3 cp source.zip "uns-mehedi-a6a1-s3-e2e-runner-builds"
